# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "iso-codes"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marius L. J\u{f8}hndal"]
  s.date = "2012-01-26"
  s.description = "A database of ISO language and script codes."
  s.email = "mariuslj (at) ifi [dot] uio (dot) no"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "iso-codes.gemspec",
    "lib/iso-639-3-macrolanguages_20100128.tab.gz",
    "lib/iso-639-3_20110525.tab.gz",
    "lib/iso_codes.rb",
    "test/test_iso_codes.rb"
  ]
  s.homepage = "http://github.com/mlj/iso-codes"
  s.require_paths = ["lib"]
  s.rubyforge_project = "iso-codes"
  s.rubygems_version = "1.8.11"
  s.summary = "ISO language and script code support"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

