# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{iso-codes}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marius L. J\303\270hndal"]
  s.date = %q{2010-06-29}
  s.description = %q{A database of ISO language and script codes.}
  s.email = %q{mariuslj (at) ifi [dot] uio (dot) no}
  s.extra_rdoc_files = [
    "README.rdoc",
     "README.todo"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "iso-codes.gemspec",
     "lib/iso-639-3-macrolanguages_20100128.tab.gz",
     "lib/iso-639-3_20100330.tab.gz",
     "lib/iso_codes.rb",
     "test/test_iso_codes.rb"
  ]
  s.homepage = %q{http://github.com/mlj/iso-codes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{iso-codes}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ISO language and script code support}
  s.test_files = [
    "test/test_iso_codes.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

